name: test

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  pytest:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
            python-version: '3.8'
      - name: Setup poetry
        uses: abatilo/actions-poetry@v2.1.0
        with:
          poetry-version: 1.1.7
      - name: Install dependencies
        run:
          poetry install
      - name: Run pytest
        run:
          poetry run pytest --cov=src --verbose --cov-report=xml
      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v2
